---

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# https://github.com/chaosmail/ansible-roles-sublime-text
# https://gist.github.com/amberj/5166112
# https://stackoverflow.com/questions/192292/how-best-to-include-other-scripts !!!
# https://github.com/chaosmail/ansible-roles-sublime-text
