---
- hosts: local

  vars_prompt:
    - name: mas_email
      prompt: "What is your icloud username?"
      private: false

    - name: mas_password
      prompt: "What is your icloud password?"
      private: true
      unsafe: true

    - name: gpg_signing
      prompt: >
        Do you want to use GPG signing? You will have to provide your short GPG ID?
        no(default)=skip, yes=execute gpg signing tasks
      private: false
      default: false

    - name: gpg_id
      prompt: >
        What's your GPG key's short ID? Leave blank if don't have one...
      private: false

  vars_files:
    - group_vars/main.yml
    - group_vars/dotfiles.yml
    - group_vars/homebrew-taps.yml
    - group_vars/homebrew.yml
    - group_vars/homebrew-casks.yml
    - group_vars/mas.yml
    - group_vars/packages.yml
    - group_vars/sublime-text.yml
    - group_vars/dock.yml
    - group_vars/sudoers.yml

  pre_tasks:
    - name: Include custom playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - role: lotyp.dnsmasq
      when: configure_dnsmasq
      tags: ['dnsmasq']

    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - role: lotyp.terminal
      when: configure_terminal
      tags: ['terminal']

    - role: lotyp.osxconfig
      when: configure_osx
      tags: ['osx']

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']
