---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: lotyp.dnsmasq
  #- name: lwalley.iterm2

collections:
  - name: geerlingguy.mac
  - name: community.general
