---

# Custom Terminal theme.
- name: Get current Terminal profile.
  ansible.builtin.command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  ansible.builtin.copy:
    src: files/terminal/Monokai-Pro.terminal
    dest: /tmp/Monokai-Pro.terminal
    mode: 0644
  changed_when: false
  when: "'Monokai Pro (Filter Spectrum)' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is added.
  ansible.builtin.command: open /tmp/Monokai-Pro.terminal
  changed_when: false
  when: "'Monokai Pro (Filter Spectrum)' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  ansible.builtin.command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string Monokai-Pro
    - defaults write com.apple.terminal 'Startup Window Settings' -string Monokai-Pro
  changed_when: false
  when: "'Monokai Pro (Filter Spectrum)' not in terminal_theme.stdout"
