---

# Set to 'true' to configure the Dock via https://github.com/kcrawford/dockutil.
configure_dock: true
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5
