---

homebrew_cask_apps:
  #
  ######################################## Browsing
  #
  - firefox
  - google-chrome
  - tor-browser
  #
  ######################################## Compression
  #
  - betterzip
  - keka
  - kekaexternalhelper
  #
  ######################################## Databases
  #
  - navicat-premium-alt
  # - sequel-ace
  # - tableplus
  #
  ######################################## Developer Utilities
  #
  - cheatsheet # https://www.mediaatelier.com/CheatSheet - Hold the ⌘-Key to get a list of all active shortcuts of the current application.
  - dash-alt
  - docker
  - github
  - iterm2
  - paw-alt
  - postman
  - ssh-config-editor-alt
  #
  ######################################## Drivers
  #
  - chromedriver # https://chromedriver.chromium.org/
  - logitech-options
  #
  ######################################## Editors
  #
  # - coderunner-alt
  - jetbrains-toolbox
  # - sublime-merge-dev
  - sublime-merge-dev-alt
  # - sublime-text-dev
  - sublime-text-dev-alt
  - tinkerwell # https://tinkerwell.app/ - Must-have tinker tool for every PHP and Laravel developer.
  - typora # https://typora.io - Simple and configurable document editor that provides excellent Markdown support.
  #
  ######################################## Entertainment
  #
  # - deezer
  - elmedia-player-alt
  # - spotify
  # - vlc
  # - webtorrent
  #
  ######################################## File Transferring
  #
  - cyberduck
  - forklift-alt
  - transmission
  # - transmit
  #
  ######################################## Fonts
  #
  - font-fira-code
  - font-hack-nerd-font
  - font-meslo-for-powerline
  #
  ######################################## Helpers
  #
  # https://github.com/sindresorhus/quick-look-plugins
  - apparency
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlstephen
  - qlvideo
  - quicklook-json
  - quicklookase
  - suspicious-package
  #
  ######################################## Messaging
  #
  - discord
  # - microsoft-teams
  - skype
  # - slack
  - telegram
  - whatsapp
  # - zoom
  #
  ######################################## Productivity
  #
  # - be-focused-pro-alt
  - focus-alt
  - miro
  - notion
  - obsidian
  - staruml-alt
  - todoist
  #
  ######################################## Security
  #
  - 1password-beta
  - adguard
  - adguard-vpn
  - cryptomator
  - gpg-suite-no-mail
  # - https://github.com/Free-GPGMail/Free-GPGMail Should be installed separately as mail bundle plugin.
  - lulu
  - ngrok
  - nordvpn
  # - tunnelblick
  #
  ######################################## Storage
  #
  - dropbox
  - google-drive
  # - megasync
  #
  ######################################## Utilities
  #
  - a-better-finder-rename-alt
  - alfred-alt
  - appcleaner
  # - new-file-menu-alt
  - numi-alt # https://github.com/nikolaeu/numi - Beautiful calculator app for macOS
  #
  ######################################## Virtualization
  #
  # - vagrant
  - virtualbox
