---

homebrew_installed_packages:
  ################## Core formulates
  - coreutils
  - moreutils
  - findutils
  - bash
  - autoconf
  - gpg
  - make
  - openssl
  - gnu-sed
  - gnupg
  - grep
  ################################ Other
  - act
  - bfg
  - composer
  - cowsay
  - curl
  - dive
  - dockerize
  - dockutil
  - gettext
  - gh
  - git
  - git-lfs
  - gmp
  - go
  - helm
  - htop
  - httpie
  - hub
  - iperf
  - jq
  - kafka
  - kubectx
  - libevent
  - lua
  - lynx
  - mackup
  - mcrypt
  - midnight-commander
  - mkcert
  - mpdecimal
  - nano
  - nmap
  - node
  - nss
  - nvm
  - openjdk
  - openssh
  - pgcli
  - php
  - postgresql
  - pre-commit
  - pv
  - rcm
  - readline
  - rlwrap
  - rtmpdump
  - screen
  - shellcheck
  - sqlite
  - ssh-copy-id
  - terraform
  - tidy-html5
  - tmux
  - tree
  - typescript
  - vbindiff
  - vim
  - wget
  - whalebrew
  - wrk
  - xz
  - zsh-history-substring-search
