---

configure_iterm2: true

iterm2_fonts:
  - url: https://github.com/powerline/fonts/blob/master/Meslo%20Slashed/Meslo%20LG%20M%20Regular%20for%20Powerline.ttf?raw=true
# GUIDs for dynamic profile must be unique, if one already exists the
# profile will not be loaded.
iterm2_dynamic_profiles:
  - url: https://api.bitbucket.org/2.0/repositories/example/example/src/master/iTerm2/DynamicProfiles/example.json
    user: example
    password: 123abc
iterm2_dynamic_profiles_local:
  - ~/path/to/profiles/example.json
iterm2_preferences_custom_folder: ~/example/iTerm2/Preferences
# If loading preferences from a custom folder your default profile GUID
# will likely already be set, so you can skip adding the profile GUID.
iterm2_default_profile_guid: 40B423CE-3599-4BF2-8C92-33CE033157B1
iterm2_shell_integration: true
