---

mas_email: ""
mas_password: ""

mas_uninstalled_apps:
  - {id: 682658836, name: "GarageBand"}

mas_installed_apps:
  - {id: 497799835, name: "Xcode"}
  - {id: 1482454543, name: "Twitter"}
  - {id: 1477385213, name: "Save to Pocket"}
  - {id: 1529448980, name: "Reeder 5."}
  - {id: 1559269364, name: "Notion Web Clipper"}
  - {id: 937984704, name: "Amphetamine"}
  - {id: 1509405283, name: "Moment - Every Day Counts! (1.3.2)"} # https://fireball.studio/moment
