---

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - name: "friendsofphp/php-cs-fixer"
  - name: "phpmd/phpmd"
  - name: "squizlabs/php_codesniffer"
  - name: "phpunit/phpunit"
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
# https://docs.ansible.com/ansible/latest/collections/community/general/pear_module.html
pear_packages:
  - name: xdebug
  - name: mpdecimal
